### ISSUE TITLE
OMOP Vocabulary in FHIR

### ISSUE THREAD

**Issue by chrisroederucdenver** [HOT-Ecosystem/hapi-issues#31]
Loading OMOP vocabulary in FHIR could mean a few different things:

- For terms from outside OMOP, we could cross check their loads from native sources with OMOP and make sure we have the terms included in omop.
- For terms inside, we need to organize/decide on how to refer to them. Maybe you get an OMOP code system and use the concept_id as a Code. Not sure what concpet_code those terms have. 
- is domain needed? They might be better represented as value sets. I'm familliar with using these values to direct a data element to the right OMOP table based on the concept's domain _id.
- how to handle conflicts between an OMOP release and native-source versions of the ontologies.

**Comment by joeflack4** [comment]
Per @stephanieshong suggestion:
### Relationship table: Create SSSOM Concept maps
Split the table by code system. Then, for each code system, create a ConceptMap resource (w/ SSSOM extensions) mapping between the CodeSystem and OMOP. Then store on GitHub and upload to FHIR server. Shahim added that in order to support certain operations (if we want/need), we would need to upload ValueSets and link to ConceptMap. I _think_ that the ValueSets would simply be lists of all the codes in a given code system (and maybe one for all the codes in OMOP as well).

**Comment by chrisroederucdenver** [comment]
I remember there is some kind of special value set that is defined to be all the terms in a CodeSystem. It might be in the course slides I forwarded. My money is on the notes from the basic class by Reuben.

**Comment by joeflack4** [comment]
We've got an initial implementation of this. I may re-open this or refer to it as/in a grouping issue, as OMOP will likely be worked on more in the uture.
